---
output:
    html_document:
        css: style.css
chunk_output_type: console
header-includes:
- \pagenumbering{gobble}
params:
    set_title: "Figure-4"
title: "`r params$set_title`"
---


```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, autodep = knitr::dep_prev())
source(here::here('r/prerequisites.R'))

d_clinical <- fread(here('data/data_clinical.txt.gz'),select=c('Tumor_Sample_Barcode','exclude'))

## load starting datasets
d_mutations <- fread(here('data/data_mutations.txt.gz'),select=c('Tumor_Sample_Barcode','PATIENT_ID','exclude','Hugo_Symbol','Role','putative_resistance_mutation',
                                                              'Variant_Classification','Variant_Type','tcn', 'mutationid', 'high_tmb','hotspot_class',
                                                              'tm','hotspotid','HGVSp_Short','truncating','Reference_Allele','Tumor_Seq_Allele2',
                                                              'Start_Position','End_Position'))

```

***

\pagebreak

# Fig 4a

```{r panel_4a, fig.width=8,fig.height=6}
## plot colors
cols <- c('#EF7B64','#1A89AD','#70C1DF','#BFBFBE')
names(cols) <- c('Gene + Residue','Gene','Residue','Not significant')

## load data for gene and residue enrichment for composite mutations
gene_enrichment <- fread(here('data/gene_enrichment_precalculated.txt'))
residue_enrichment <- fread(here('data/residue_enrichment_precalculated.txt'))

## merge in gene enrichment data and plot
gene_enrichment <- gene_enrichment[,c('Hugo_Symbol','q_enriched'),with=F]
setnames(gene_enrichment,'Hugo_Symbol','query_gene')
residue_enrichment <- residue_enrichment[,c('query_gene','query_mutation','q.value.enriched'),with=F]
setnames(residue_enrichment,'q.value.enriched','q.value')
dat <- merge(residue_enrichment,gene_enrichment,by='query_gene',all.x=T)
names(dat) <- c('gene','residue','q.residue','q.gene')
dat$nlog10q.gene <- -log10(dat$q.gene)
dat$nlog10q.residue <- -log10(dat$q.residue)

## additional formatting for plot
gene_labs <- dat[q.gene < 0.01,c('gene','q.gene'),with=F]
gene_labs <- gene_labs[!duplicated(gene),]
gene_labs$nlog10q.gene <- -log10(gene_labs$q.gene)
gene_labs$sig <- 'Not significant'
gene_labs[q.gene < 0.01,sig:='Gene']
gene_labs$sig <- factor(gene_labs$sig,levels=names(cols))
residue_labs <- dat[(q.residue < 0.01 & q.gene < 0.01) | (q.residue < 1e-3 & q.gene >= 0.01) ,c('gene','residue','q.gene','q.residue'),with=F]
residue_labs <- residue_labs[!duplicated(residue),]
residue_labs$nlog10q.gene <- -log10(residue_labs$q.gene)
residue_labs$nlog10q.residue <- -log10(residue_labs$q.residue)
residue_labs <- residue_labs[order(gene,q.residue,decreasing=F),]

topN_per_gene <- function(d,n) {
    d <- d[order(q.residue,decreasing=F),]
    d[1:n,]
}
top3_genes <- c('APC','PIK3CA','TP53','EGFR')
residue_labs3 <- residue_labs[gene %in% top3_genes,topN_per_gene(.SD,3),by=gene]
top1_genes <- c('PTEN','MAP3K1','FBXW7','TERT','BRAF','ERBB2','FGFR2')
residue_labs1 <- residue_labs[gene %in% top1_genes,topN_per_gene(.SD,1),by=gene]
residue_labs_other <- residue_labs[gene %nin% c(top3_genes,top1_genes),topN_per_gene(.SD,1),by=gene]
residue_labs_other$residue <- NA
residue_labs <- rbind(residue_labs3, residue_labs1, residue_labs_other)

residue_labs <- residue_labs[!is.na(q.residue)]
residue_labs$sig <- 'Not significant'
residue_labs[q.residue < 0.01 & q.gene < 0.01,sig:='Gene + Residue']
residue_labs[q.residue >= 0.01 & q.gene < 0.01,sig:='Gene']
residue_labs[q.residue < 0.01 & q.gene >= 0.01,sig:='Residue']
residue_labs$sig <- factor(residue_labs$sig,levels=names(cols))

sig_val <- -log10(0.01)
dat$sig <- 'Not significant'
dat[q.residue < 0.01 & q.gene < 0.01,sig:='Gene + Residue']
dat[q.residue >= 0.01 & q.gene < 0.01,sig:='Gene']
dat[q.residue < 0.01 & q.gene >= 0.01,sig:='Residue']
dat$sig <- factor(dat$sig,levels=names(cols))

dat[is.infinite(nlog10q.gene),nlog10q.gene:=200]
dat <- dat[!is.na(q.gene),]
gene_labs[is.infinite(nlog10q.gene),nlog10q.gene:=200]
gene_labs <- gene_labs[!is.na(q.gene),]
plot_gene_labels <- c('NF1','CDKN1A','CIC','CDK12','PIK3R1')
gene_labs$label <- gene_labs$gene
gene_labs[gene %nin% plot_gene_labels,label:=NA]
residue_labs[is.infinite(nlog10q.gene),nlog10q.gene:=200]
residue_labs <- residue_labs[!is.na(q.gene),]

## broken x-axis
x_info <- break_axis(dat$nlog10q.gene,maxlower=30,minupper=50,lowerticksize=5,upperticksize=50,ratio_lower_to_upper=0.45)
dat$nlog10q.gene.new <- x_info$newy
x_info_gene_labs <- break_axis(gene_labs$nlog10q.gene,maxlower=30,minupper=50,lowerticksize=5,upperticksize=50,ratio_lower_to_upper=0.45)
gene_labs$nlog10q.gene.new <- x_info_gene_labs$newy
x_info_residue_labs <- break_axis(residue_labs$nlog10q.gene,maxlower=30,minupper=50,lowerticksize=5,upperticksize=50,ratio_lower_to_upper=0.45)
residue_labs$nlog10q.gene.new <- x_info_residue_labs$newy

## broken y-axis
y_info <- break_axis(dat$nlog10q.residue,maxlower=10,lowerticksize=2,upperticksize=5,ratio_lower_to_upper=0.25)
dat$nlog10q.residue.new <- y_info$newy
y_info_residue_labs <- break_axis(residue_labs$nlog10q.residue,maxlower=10,lowerticksize=2,upperticksize=5,ratio_lower_to_upper=0.25)
residue_labs$nlog10q.residue.new <- y_info_residue_labs$newy

## make plot
p <- ggplot(dat,aes(x=nlog10q.gene.new,y=nlog10q.residue.new)) +
    geom_hline(yintercept=sig_val,color='grey',size=0.5,linetype='dashed') +
    geom_vline(xintercept=sig_val,color='grey',size=0.5,linetype='dashed') +
    geom_point(aes(color=sig),size=1.2) +
    geom_text_repel(data=residue_labs,aes(x=nlog10q.gene.new,y=nlog10q.residue.new,label=residue,color=sig),
                    min.segment.length=0.001,angle=0,hjust=0,vjust=0.5) +
    geom_text_repel(data=gene_labs,aes(x=nlog10q.gene.new,label=label,color=sig),y=0,angle=90,hjust=1.2,vjust=0.5) +
    scale_x_continuous(limits=x_info$limits,labels=x_info$labels,breaks=x_info$breaks) +
    scale_y_continuous(limits=c(-0.5,y_info$limits[2]),labels=y_info$labels,breaks=y_info$breaks) +
    scale_color_manual(values=cols,name='Leve of enrichment\n(composites):') +
    theme_classic(base_family='ArialMT',base_size=14) +
    theme(legend.position='bottom') +
    labs(x='Gene -log10(q-value)',y='Residue -log10(q-value)')
p

```

***

\pagebreak

# Fig 4b

```{r, panel_4b}

## load experimental data
d <- fread(here('data/tert_rlu_luciferase.txt'))
setnames(d,'cell line','line')
d <- melt(d,id.vars=c('Replicate','line'))
d$id <- paste(d$variable,d$line)

## calculate significance between alleles (controlling for cell line)
test <- function(allele1, allele2, d) {
    tmp <- d[variable %in% c(allele1, allele2),]
    tmp$allele1 <- tmp$variable==allele1
    m <- lm(value ~ allele1 + line, data=tmp)
    out <- Anova(m, type="II")
    p.anova <- as.numeric(adt(out)[1,4])
    data.table(allele1=allele1,allele2=allele2,p.anova=p.anova)
}
x1 <- test('WT','205C>T',d)
x2 <- test('WT','228C>T',d)
x3 <- test('WT','250C>T',d)
x4 <- test('WT','228C>T + 205C>T',d)
x5 <- test('WT','250C>T + 205C>T',d)
x6 <- test('228C>T','228C>T + 205C>T',d)
x7 <- test('250C>T','250C>T + 205C>T',d)
out <- rbind(x1,x2,x3,x4,x5,x6,x7)
out$p.anova <- paste0('p=',prettyNum(out$p.anova,digits=1))
out$id1 <- paste(out$allele1,'Sk-Mel2')
out$id2 <- paste(out$allele2,'Sk-Mel2')


## collapse replicates by mean +/- sem
collapse_replicates <- function(d) {
    mu <- mean(d$value)
    n <- nrow(d)
    sem <- sd(d$value)/sqrt(n)
    list(mu=mu,sem=sem)
}
d2 <- d[,collapse_replicates(.SD),by=c('variable','line')]
d2$lwr <- d2$mu - d2$sem
d2$upr <- d2$mu + d2$sem
d2$id <- paste0(d2$variable,' ',d2$line)
d2$line <- factor(d2$line, levels=c('A375','Sk-Mel2','Sk-Mel30'))
d2 <- d2[order(variable,line)]
d2$id <- factor(d2$id, levels=d2$id)
d$id <- factor(d$id, levels=d2$id)

## hardcode the positions for the lines comparing significance
out2 <- out
allele_levels=unique(d$variable)
out2$allele1 <- factor(out2$allele1,levels=allele_levels)
out2$allele2 <- factor(out2$allele2,levels=allele_levels)
index <- c(1,6,7,2,4,3,5)
out2 <- out2[index,]
out2$ypos <- c(55,325,250,400,425,450,475)

## define colors
line_colors <- c('#B7DBEB','#70C1DF','#1A89AD')
names(line_colors) <- levels(d$line)

## make plot
p <- ggplot() +
    geom_bar(data=d2, aes(x=id,y=mu,fill=line), stat="identity") +
    geom_errorbar(data=d2,aes(x=id,ymin=lwr,ymax=upr),width=0, colour="black") +
    geom_point(data=d,aes(x=id,y=value),pch=19,position=position_jitter(0.1)) +
    scale_fill_manual(values=line_colors, name=NULL) +
    theme_std(base_size=14) +
    theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1)) + 
    scale_y_continuous(expand=c(0,0), breaks=seq(0,350,by=50),limits=c(0,550)) +
    labs(x='TERT promoter allele',y='RLU Luciferase') 
    for(i in 1:nrow(out2)) p <- p + geom_signif(comparisons=list(c(out2$id1[i],out2$id2[i])), 
                                                y_position = out2$ypos[i] + 5,
                                                annotations=out2$p.anova[i],family='ArialMT',size=0.5,tip_length=0)

p
```



